### ISSUE TITLE
还是有报错

### ISSUE THREAD

**Issue by Gx952743985** [mxl123/IDAndBankCard#1]
你说的那个地方我关了,还是报错
![12](https://cloud.githubusercontent.com/assets/16395032/22095769/6b1dc34a-de52-11e6-833e-4a2b83465304.png)
![123](https://cloud.githubusercontent.com/assets/16395032/22095770/6b76bfe0-de52-11e6-9eb7-6112f48f4f81.png)

**Comment by mxl123** [comment]
关那个是针对arm64的报错，你这个是用的模拟器调试吧，只能用真机
