### ISSUE TITLE
IDAndBankCard 模拟器编译报错

### ISSUE THREAD

**Issue by prcliyong** [mxl123/IDAndBankCard#12]
Undefined symbols for architecture x86_64:
  "_EXCARDS_Init", referenced from:
      -[XLScanManagerInitialize configIDScan] in XLScanManagerInitialize.o
  "_EXCARDS_RecoIDCardData", referenced from:
      -[XLScanManagerControl parseIDCardImageBuffer:] in XLScanManagerControl.o
  "_BankCardNV12", referenced from:
      -[XLScanManagerControl parseBankImageBuffer:] in XLScanManagerControl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by prcliyong** [comment]
用真机可以运行，切换到模拟器就报上面的错误，求指教？

**Comment by RogerAbyss** [comment]
该.a文件架构只支持真机
lipo -info *.a 
查看应该没有i386

**Comment by mxl123** [comment]
楼上说的对，只支持真机

**Comment by prcliyong** [comment]
已经查看，支持i386

**Comment by mxl123** [comment]
@prcliyong 只有银行卡的支持i386，i386的模拟器架构对应的模拟器应该只有4s-5

**Comment by LinQingmo-w** [comment]
只保留银行卡的话 为什么还会报
-[XLScanManagerControl parseBankImageBuffer:] in XLScanManagerControl.o
ld: symbol(s) not found for architecture x86_64

**Comment by LinQingmo-w** [comment]
-[XLScanManagerControl parseBankImageBuffer:] in XLScanManagerControl.o
ld: symbol(s) not found for architecture x86_64 
这个报错  在 XLScanManagerControl  resultLen = BankCardNV12(...  那一段的判读 用 #if !TARGET_IPHONE_SIMULATOR#endif 给包起来了 然后模拟器就可以运行了   应该有更好的办法
