### ISSUE TITLE
在Xcode 8.3 上编译过不去

### ISSUE THREAD

**Issue by AnswerXu** [mxl123/IDAndBankCard#13]
大牛你好，看了你的IDAndBankCard,你的Demo是可以跑起来的，但是如果我想自己新建工程集成的话编译会出错(Xcode 8.3.3上)，尝试了你给出的解决方法还是没用，不知是否还有其他解决办法，还请不吝赐教，感谢

**Comment by AnswerXu** [comment]
已解决：1. Build Settings -> Other Linker Flags  添加-ObjC
              2. Build Settings -> Enable Bitcode  修改为No
以上操作应该就能解决静态库编译问题

**Comment by appsming** [comment]
大神，我也遇到编译问题。总是报错。   已按上面的操作了。 1. Build Settings -> Other Linker Flags 添加-ObjC
2. Build Settings -> Enable Bitcode 修改为No

Showing Recent Messages
  "_EXCARDS_Init", referenced from:
      -[XLScanManagerInitialize configIDScan] in XLScanManagerInitialize.o
  "_EXCARDS_RecoIDCardData", referenced from:
      -[XLScanManagerControl parseIDCardImageBuffer:] in XLScanManagerControl.o
  "_BankCardNV12", referenced from:
      -[XLScanManagerControl parseBankImageBuffer:] in XLScanManagerControl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mxl123** [comment]
@appsming 用真机调试，不支持模拟器
