### ISSUE TITLE
在真机上没问题，在模拟器上会出错

### ISSUE THREAD

**Issue by vast0608** [mxl123/IDAndBankCard#4]
你好，很感谢你提供了这么好的开源项目，在运行你项目的过程中我发现了一些小问题，我在真机上测试是很顺利的（iPhone7  iOS10.2.1）,但是用模拟器就会报错（Xcode8.2.1），希望在你方便的时候可以维护一下

**Comment by mxl123** [comment]
项目的.a核心文件来自于网络，我只找到几个真机架构的包，暂时还没有模拟器版本的

**Comment by vast0608** [comment]
好的，谢谢你了，明白了

发自我的 iPhone
