### ISSUE TITLE
我迁移文件,这个问题找了好久没找出来

### ISSUE THREAD

**Issue by zhumingjun9** [mxl123/IDAndBankCard#7]
Undefined symbols for architecture arm64:
  "_ZIM_SaveImage", referenced from:
      ImgSave(tagIMG, char const*) in libbankcard.a(gjimage.o)
  "_ZIM_LoadImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbankcard.a(gjimage.o)
  "_ZIM_DoneImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbankcard.a(gjimage.o)

**Comment by zhumingjun9** [comment]
已解决  build setting - enable testability  设置为NO

**Comment by mxl123** [comment]
不好意思，一直没查看邮件，解决了就好




发自网易邮箱大师
在2017年05月16日 17:21，BBQ 写道：

已解决 build setting - enable testability 设置为NO
