### ISSUE TITLE
你好一直报这个错误怎样解决

### ISSUE THREAD

**Issue by xjp694762617** [mxl123/IDAndBankCard#9]
ld: '/Users/hxxc/Desktop/IDAndCarXjp/IDAndCarXjp/bank_io/exbankcardcore/libbankcard.a(exbankcardcore.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mxl123** [comment]
build setting里边把bitcode关了
